name: Example workflow for Golang using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: json 
      - name: Upload vulnerability report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: snyk_results.json
          path: ./snyk.json
          if-no-files-found: warn
